DROP DATABASE IF EXISTS PIXEL_EMPORIUM;
CREATE DATABASE PIXEL_EMPORIUM;
USE PIXEL_EMPORIUM;

CREATE TABLE GIOCO(
PREFISSO_ID CHAR(1) NOT NULL,
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
DESCRIZIONE VARCHAR(65536) NOT NULL,
IMMAGINE BLOB NOT NULL,
MARCHIO VARCHAR(255) NOT NULL,
PREZZO DECIMAL(5,2) NOT NULL,
ANNO_DI_RILASCIO YEAR NOT NULL,
GENERE VARCHAR(255),
PEGI VARCHAR(2),
FORMATO VARCHAR(8) NOT NULL,
CONSTRAINT FORMATO_GIOCO CHECK(FORMATO='FISICO' OR FORMATO='DIGITALE'),
CONSTRAINT PREFISSO_ID CHECK (PREFISSO_ID='G'));

CREATE TABLE COMPATIBILITA_GIOCO(
ID_GIOCO INT REFERENCES GIOCO(ID),
ID_CONSOLE INT REFERENCES CONSOLE(ID),
PRIMARY KEY(ID_GIOCO, ID_CONSOLE));

CREATE TABLE CONSOLE(
PREFISSO_ID CHAR(1) NOT NULL,
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
DESCRIZIONE VARCHAR(65536) NOT NULL,
IMMAGINE BLOB NOT NULL,
MARCHIO VARCHAR(255) NOT NULL,
PREZZO DECIMAL(5,2) NOT NULL,
ANNO_DI_RILASCIO YEAR NOT NULL,
SUPPORTI VARCHAR(13) NOT NULL,
RETROCOMPATIBILITA BOOLEAN,
ARCHIVIAZIONE VARCHAR(255),
GENERAZIONE INT,
CONSTRAINT SUPPORTO_CONSOLE CHECK(SUPPORTI='DISCHI' OR SUPPORTI='CARTUCCIA' OR SUPPORTI='SOLO DIGITALE')
CONSTRAINT PREFISSO_ID CHECK (PREFISSO_ID='C'));

CREATE TABLE COMPATIBILITA_ACCESSORIO(
ID_ACCESSORIO INT REFERENCES ACCESSORIO(ID),
ID_CONSOLE INT REFERENCES CONSOLE(ID),
PRIMARY KEY(ID_GIOCO, ID_CONSOLE));

CREATE TABLE ACCESSORIO(
PREFISSO_ID CHAR(1) NOT NULL,
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
DESCRIZIONE VARCHAR(65536) NOT NULL,
IMMAGINE BLOB NOT NULL,
MARCHIO VARCHAR(255) NOT NULL,
PREZZO DECIMAL(5,2) NOT NULL,
TIPO_ACCESSORIO VARCHAR(255) NOT NULL,
CONSTRAINT PREFISSO_ID CHECK (PREFISSO_ID='A'));